# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfile',
            name='count_found',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadfile',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadfile',
            name='position_found',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadfile',
            name='time_search',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loadfile',
            name='file_obj',
            field=models.FileField(upload_to=''),
        ),
    ]
